### ISSUE TITLE
Requirements - history

### ISSUE THREAD

**Issue by dimitarpeikov** [Flash-SDAI/Flash#1]
To update a file, you need to upload new revision of the same file. It is not expected to create new file per revision. Just commit new file!
Each update shall have summary of the change ... How to read "Added files via upload"?
Don't change it now - new revisions shall have summary of the change.

**Comment by rgg1992** [comment]
Dear Dimitar,

thank you for your comment, we will have it in mind in our future development and future uploads.

I am closing this issue but please don't hesitate to contact us if you have any other notes you want to discuss with our team.

Best Regards,
Radoslav
